### PR TITLE
Integrate retry mechanism

### LINKED ISSUE #75: Audit randomly fails due to 503 (Yarn and NPM)
Hello,

I am using `audit-ci` in my CircleCI workflow (thank you for this package). I have a annoying issue: sometimes, the audit fails with the error:

```
Invocation of npm audit failed:
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-04-03T14_57_17_893Z-debug.log
Exiting...
```

I understand this seems to be an error from NPM server and not `audit-ci` itself, however, I never encountered this error while running `npm audit` locally on the project.

This error is very random: sometimes it occurs 5 times in a row, sometimes it does not happen for days.

Did some of you stumble upon this issue? Do you know if we can implement some kind of retying mechanism in `audit-ci` to circumvent it?

Thank you

### PR DESCRIPTION
**Pull request by djomaa**
Fixes #75
Now if audit fails due to npm registry, it's repeated up to 5 times.

Probably, it would be cool to create parameters for retry delay and retry max attempts.

### CODE REVIEW

File: lib/npm-auditer.js [hunk 1]
```diff
@@ -6,6 +6,9 @@
 const { runProgram, reportAudit } = require('./common');
 const Model = require('./Model');
 
+const RETRY_ERROR_MSG =
+  'npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests.';
```
Comment (quinnturner) [inline lib/npm-auditer.js]: Since we use the `--registry` flag, this may not be the correct error message since `https://registry.npmjs.org/` may be incorrect. Perhaps simplify it to `'does not support audit requests.'` or pass in the `--registry` variable and make `RETRY_ERROR_MSG` a function. If the NPM error message changes in the future this is brittle, but it is undoubtedly better than the existing setup.

File: lib/yarn-auditer.js [hunk 2]
```diff
@@ -46,118 +48,127 @@ function yarnAuditSupportsRegistry(yarnVersion) {
...
+          const summary = model.getSummary(a => a.id);
+          return reporter(summary, config);
+        }
+      );
+    })
+    .catch(err => {
+      const message = err.message || err;
+      if (message && message.includes(RETRY_ERROR_MSG) && attempt < 5)
+        return audit(config, reporter, attempt + 1);
+      if (message && message.includes(RETRY_ERROR_MSG) && attempt < 5)
```
Comment (quinnturner) [inline lib/yarn-auditer.js]: Fix: duplicate code

**Comment by quinnturner** [comment]
I agree that the retry attempt should be configurable. Perhaps the following specification?

Arg: _none_
Alias: `retry-count`
Description: _The number of attempts `audit-ci` calls an unavailable registry before failing (default `5`)_

Placing this ^ after `--registry` in the various README options.

Config file spec:
"retry-count": <integer> // [Optional] defaults `5`

Also, we should consider documenting this behaviour in the README.

> If the registry's service is unavailable, `audit-ci` will re-run _5_ times before failing unless otherwise specified with `--retry-count`. This behaviour has been noted in https://github.com/IBM/audit-ci/issues/75.

**Comment by djomaa** [comment]
@quinnturner all is ready.

I also changed audit start flow for the availability of the mechanism in tests

**Comment by quinnturner** [comment]
Created https://github.com/djomaa/audit-ci/pull/1 for some minor fixes.

It would be a nice-to-have having a test that fails at first due to a 503 then passes. However, it's okay if that is added later.
